{"access_token":
{"created_at":"2012/10/27 20:45:28 +0000",
"network_name":"hacktoberfest.onmicrosoft.com",
"network_id":480183,
"view_messages":true,
"view_groups":true,
"authorized_at":"2012/10/27 20:45:27 +0000",
"token":"UPHfq3mR70BndCMQzHtoww",
"view_subscriptions":true,
"modify_subscriptions":true,
"user_id":1490226512,
"expires_at":null,
"view_members":true,
"network_permalink":"hacktoberfest.onmicrosoft.com",
"modify_messages":true,"view_tags":true},
"network":
{"created_at":"2012/10/20 00:33:18 +0000","profile_fields_config":
{"enable_job_title":true,"enable_work_phone":true,"enable_mobile_phone":true},
"navigation_background_color":"#38699F",
"community":false,"header_background_color":"#e3be91",
"permalink":"hacktoberfest.onmicrosoft.com","is_org_chart_enabled":true,
"id":480183,"is_group_enabled":true,"navigation_text_color":"#FFFFFF",
"web_url":"https://www.yammer.com/hacktoberfest.onmicrosoft.com",
"is_chat_enabled":true,"type":"network","header_text_color":"#e3be91",
"name":"hacktoberfest.onmicrosoft.com","paid":true,"show_upgrade_banner":false},
"user":{"schools":[],
"mugshot_url":"https://mug0.assets-yammer.com/mugshot/images/48x48/no_photo.png",
"timezone":"Pacific Time (US \u0026 Canada)","job_title":"",
"network_name":"hacktoberfest.onmicrosoft.com","first_name":"Moon","interests":null,
"mugshot_url_template":"https://mug0.assets-yammer.com/mugshot/images/{width}x{height}/no_photo.png",
"network_id":480183,"admin":"false","contact":{"phone_numbers":[],"im":{"username":"","provider":""},
"email_addresses":[{"type":"primary","address":"moon@hacktoberfest2012.onmicrosoft.com"}]},
"stats":{"updates":1,"following":0,"followers":1},"state":"active","guid":null,"id":1490226512,
"expertise":null,"full_name":"Moon Limb","birth_date":"","show_ask_for_photo":true,
"can_broadcast":"false","department":null,"settings":{"xdr_proxy":"https://xdrproxy.yammer.com"},
"kids_names":null,"web_url":"https://www.yammer.com/hacktoberfest.onmicrosoft.com/users/moon",
"previous_companies":[],"verified_admin":"false","type":"user","hire_date":null,"external_urls":[],
"last_name":"Limb","location":null,"name":"moon","significant_other":null,
"url":"https://www.yammer.com/api/v1/users/1490226512",
"network_domains":["hacktoberfest.onmicrosoft.com","hacktoberfest2012.onmicrosoft.com"],"activated_at":"2012/10/27 20:37:05 +0000","summary":null}}